export const GET_ALL_WISHLIST = 'GET_ALL_WISHLIST';
export const DELETE_ONE_WISHLIST = 'DELETE_ONE_WISHLIST';

export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_SERECH_PRODUCTS = 'GET_SERECH_PRODUCTS';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';

export const GET_ALL_CMMENTS = 'GET_ALL_CMMENTS';
export const ADD_CMMENTS = 'ADD_CMMENTS';
export const EDITE_CMMENTS = 'EDITE_CMMENTS';
export const DELETE_CMMENTS = 'DELETE_CMMENTS';
